export const API_AUTH_LOGAR = '@AUTH/API_AUTH_LOGAR';
export const SET_LOGAR = '@AUTH/SET_LOGAR';
export const SET_AUTH_VALUES = '@AUTH/SET_AUTH_VALUES';
export const SET_DADOS_CLIENTE_LOGADO = '@AUTH/SET_DADOS_CLIENTE_LOGADO';